### ISSUE TITLE
republish to pypi

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord-dev/tx-shared-tools#10]
@richmahn I'm trying to use the read_file method from this but it appears pypi hasn't been updated for some time.
Could you re-publish this to pypi so I can use the latest tools in my libs?

**Comment by da1nerd** [comment]
I realize it's trivial to read a file but I've noticed this method being used in a number of places and I'm bewildered as to how things have not broken.

**Comment by richmahn** [comment]
We gave up tx-shared-tools for tx-manager and have the general_tools in there.

**Comment by richmahn** [comment]
Where do you see it used many places?

**Comment by da1nerd** [comment]
I've seen it used in dokuwiki-to-rc and in d43-catalog. Not many I supposed just a few :P
